variables:
- name: _DotNetArtifactsCategory
  value: .NETCore

stages:
- stage: build
  displayName: Build
  jobs:
  - template: ../jobs/ci-linux.yml
    parameters:
      job: fedora29
      imageName: microsoft/dotnet-buildtools-prereqs:fedora-29-2f0798a-20181105183801

  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: ../../eng/common/templates/job/publish-build-assets.yml
      parameters:
        dependsOn: fedora29
        publishUsingPipelines: true
        pool:
          vmImage: vs2017-win2016
  
# Based on - https://github.com/dotnet/arcade/blob/9b3f304c7bc9fd4d11be9ca0b466b83e98d2a191/Documentation/CorePackages/Publishing.md#moving-away-from-the-legacy-pushtoblobfeed-task
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: ../../eng/common/templates/post-build/post-build.yml
    parameters:
      enableSourceLinkValidation: true
      #Nuget and Signing Validation are not needed as we use an empty placeholder nupkg which is never utilized
      enableSigningValidation: false
      enableNugetValidation: false